// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace ShaderProject
{
    [default_interface]
    runtimeclass CompilePage : Microsoft.UI.Xaml.Controls.Page
    {
        CompilePage();
    }
}
